# Generated by Django 4.1.2 on 2022-10-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatroomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=500)),
                ('youtube_video_id', models.CharField(max_length=500)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='user.usermodel')),
                ('room_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='user.usermodel')),
            ],
        ),
    ]
