# Generated by Django 4.1.2 on 2022-10-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroommodel',
            name='comments',
        ),
        migrations.AddField(
            model_name='chatroommodel',
            name='room_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
