# Generated by Django 4.1.3 on 2022-11-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_auth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='date_of_birth',
        ),
    ]
