# Generated by Django 4.1.3 on 2022-11-23 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatroomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=20)),
                ('youtube_video_id', models.CharField(max_length=500)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='user.usermodel')),
                ('room_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='user.usermodel')),
            ],
        ),
    ]
