# Generated by Django 4.1.3 on 2022-11-24 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroommodel',
            old_name='room_id',
            new_name='room_name',
        ),
    ]
